build-book:
  script: 
  - gitbook install
  - gitbook build . $WEBSITE_PATH/$CI_PROJECT_NAME
  - cd $WEBSITE_PATH
  - rm -rf $CI_PROJECT_NAME/.*
  - rm -f $CI_PROJECT_NAME.tgz
  - tar zcf $CI_PROJECT_NAME.tgz $CI_PROJECT_NAME

  stage: build